name: "setup-scala"
description: "Installs AdoptOpenJDK via Jabba"
author: "Olafur Pall Geirsson"
inputs:
  java-version:
    description: >
      GitHub Action to install any version of Java (GraalVM, Java 8, Java 11, Java 14, ...) via Jabba. Works for any JVM language including Java, Scala and Kotlin. 
    default: "adopt@1.8"
  jabba-version:
    description: The Jabba version to install.
    default: "0.11.2"
runs:
  using: "node12"
  main: "lib/main.js"
branding:
  icon: "download"
  color: "blue"
